### ISSUE TITLE
Sharing: made a port for vscode

### ISSUE THREAD

**Issue by pavalos6401** [embark-theme/vim#30]
It's not the best, and it is my first time making a vscode extension, but I thought maybe I could hand it off and someone could take it from here. In any case, I love the theme, keep up the great work!

Links:
* [Marketplace link](https://marketplace.visualstudio.com/items?itemName=pavalos6401.embark-theme-vscode)
* [Github link](https://github.com/pavalos6401/embark-theme-vscode)

**Comment by pavalos6401** [comment]
I could also help maintain it. Although I am sort of inexperienced, I'd love to learn and get some hands on experience contributing to projects

**Comment by skbolton** [comment]
Thanks for taking initiative. Work on a vscode port is long overdue. To make it easier to find embark themes I am hoping to keep them under the embark github organization. If you'd like I can create the repo and you can create a PR into it.

It looks like this is a good start but I would prefer that if it gets merged at this point it gets marked as "Work in Progress" since it looks like there is more to do.

I am also planning on updating the [site](https://embark-theme.github.io/) with some style guidelines on how the colors should be used for different elements/intentions. If you feel like this would help in working on this port I can share thoughts in the meantime.

**Comment by pavalos6401** [comment]
Hi @skbolton ! Yeah, if you make a repository I could make a PR. Would you want me to delete my extension off of the marketplace after that? or would renaming it be enough -- to avoid further confusion about which one is the official one (I was thinking of renaming mine to unembark and use it to kinda make my own spin of the scheme)? I would also rename it on my github repository if that's okay (if you want me to delete it that's understandable as well, I was kinda unoriginal and careless in my naming).

I would mark it as "Work in Progress".

If you also make the style guidelines that would be very helpful. I tried to piece together the theme using the vim theme file, but some of the identifiers where rather abstract when comparing it to how vscode does themes.

Again, I'm sorry about my lack of experience. I haven't really done much on github or the marketplace; I've only really used github for keeping some of my dotfiles, and the only PR I've done is from one branch to another when I was in a robotics team.

**Comment by skbolton** [comment]
Repo has been created [here](https://github.com/embark-theme/vscode). Feel free to open a PR there.

Also definitely keep a fork of embark if you would like to. It would be nice to have the name be available for the main branches of the theme. If you are willing to give up the name then we would just need to figure out how vscode handles transfering names to new packages and all that.

**Comment by pavalos6401** [comment]
I have made a pull request, I added some comments there; I basically just removed my original extension (which should free up naming and remove the whole transferring issue)
