### ISSUE TITLE
JavaScript: await and function name are the same color

### ISSUE THREAD

**Issue by dmshvetsov** [embark-theme/vim#38]
Hi! I liked this theme and decided to give it a try.

I have been using it for a minute or so, and I found it strange to read async / await JavaScript code. Please take a look:

<img width="757" alt="Screen Shot 2021-03-28 at 10 57 33 PM" src="https://user-images.githubusercontent.com/3574904/112753068-cd037680-8fde-11eb-81af-e3023579b048.png">

`await` is a keyword and `graphql(` in a function invocation. So it makes big difference if there is `await` or not and I used to that other themes have a separate color for keywords. In Embark you have the same color for function names and keywords.

I wonder if you think it will improve the theme if it has (at least slightly) different colors for function names and keywords?

**Comment by skbolton** [comment]
Hi @dmshvetsov. Sorry for the last response on this. Ever since I have moved embark to its own organization I haven't been the best with notifications since they no longer show up in main account.

The theme definitely needs some tweaking to cover javascript better. I don't do a lot of javascript coding these days and so I haven't seen the painpoints.  I would love any help that can be offered on this. The syntax rules defined in [this](https://github.com/pangloss/vim-javascript) plugin can be used to target specific javascript idoms to highlight them better.

In my mind `async/await` are control flow structures so they should be shown in the green color similar to the if statement [here](https://github.com/pangloss/vim-javascript)

**Comment by skbolton** [comment]
@dmshvetsov Decided to jump on and start working on this. Can you help me out and run the `js-async-await` branch and let me know what you think?

**Comment by skbolton** [comment]
Here is what on my end the highlight adjustments are looking like
![async-await](https://user-images.githubusercontent.com/13260877/115506944-b694b780-a238-11eb-9216-fdd71948de88.png)

**Comment by skbolton** [comment]
I have felt like the javascript highlighting is way too heavy on the reds and yellows so I am hopeful to introduce more of the greens and blues that I love about this palette into the rules. Again let me know what you think.

**Comment by dmshvetsov** [comment]
Hi @skbolton 👋 . I'll check it soon 👍

**Comment by dmshvetsov** [comment]
yea! I like it 👍 👍 

@skbolton how about trying to make operators like comparison `===`, `>=` etc. the same color as `if` `async/await`?

for reference:

### before
<img width="904" alt="Screen Shot 2021-04-22 at 4 14 33 PM" src="https://user-images.githubusercontent.com/3574904/115664974-f3ba9000-a385-11eb-80ee-e74b258bda82.png">

### after
<img width="904" alt="Screen Shot 2021-04-22 at 4 13 30 PM" src="https://user-images.githubusercontent.com/3574904/115664984-f74e1700-a385-11eb-8b5d-3a5e9fd95243.png">

**Comment by dmshvetsov** [comment]
> @skbolton how about trying to make operators like comparison `===`, `>=` etc. the same color as if async/await?

Using it a little more, I no longer think that it's a good idea. I like how it is right now.

**Comment by skbolton** [comment]
Yeah I actually did that at first and went back on it as well. So glad we came to the same conclusion

**Comment by skbolton** [comment]
Resolved with #39 

Closing for now. @dmshvetsov if you find other places where the syntax of javascript can be improved feel free to reach out or create a new issue. You should be able to point back to master branch and see the same changes.

**Comment by dmshvetsov** [comment]
@skbolton thanks a lot! 🙌
